version: '3.1'
services:
  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bank-manager
      POSTGRES_USER: bank-manager
      POSTGRES_PASSWORD: bank-manager